// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolERP.DataAccess.Reporting;

#nullable disable

namespace SchoolERP.DataAccess.Reporting.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SchoolERP.DataAccess.Reporting.Entities.ReportSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("ToUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ReportType", "CreatedAtUtc");

                    b.ToTable("ReportSnapshots");
                });

            modelBuilder.Entity("SchoolERP.Common.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterStateJson")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeStateJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
