// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolERP.Examination.Data;

#nullable disable

namespace SchoolERP.Examination.Migrations
{
    [DbContext(typeof(ExaminationDbContext))]
    [Migration("20260708223826_InitialMySql")]
    partial class InitialMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SchoolERP.Examination.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<string>("AnswerKeyJson")
                        .HasColumnType("json");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExamDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsResultPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxMarks")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PassingMarks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResultPublishedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId", "SubjectId", "ExamDateUtc");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("SchoolERP.Examination.Entities.MarksEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EnteredByStaffId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MarksObtained")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId", "StudentId")
                        .IsUnique();

                    b.ToTable("MarksEntries");
                });

            modelBuilder.Entity("SchoolERP.Shared.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterStateJson")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeStateJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SchoolERP.Examination.Entities.MarksEntry", b =>
                {
                    b.HasOne("SchoolERP.Examination.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });
#pragma warning restore 612, 618
        }
    }
}
